### ISSUE TITLE
Bug: No autoprefix styles applied

### ISSUE THREAD

**Issue by leroyrosales** [leroyrosales/pom-chi#22]
`<div class="flex flex-row justify-center text-white underline">Some Text</div>`  should return:

```css
.flex {

  display: -webkit-box;

  display: -webkit-flex;

  display: -ms-flexbox;

  display: flex;

}

.flex-row {

  -webkit-box-orient: horizontal;

  -webkit-box-direction: normal;

  -webkit-flex-direction: row;

      -ms-flex-direction: row;

          flex-direction: row;

}
```

However, instead it returns:

```css
.flex {
  display: flex;
}

.flex-row {
  flex-direction: row;
}
```
